name: CI-Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.10']
        experimental: [false]
    steps:
    - name: Cancel previous
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system packages
      run: |
        winget install Python.Python.3
        winget install Kitware.CMake

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      if: matrix.python-version != '3.11-dev'
      run: python build_scripts/ci_script.py

    - name: Run Tests for python 3.11
      if: matrix.python-version == '3.11-dev'
      run: python build_scripts/ci_script.py || exit 0
